# worker/wrangler.toml
name = "tarot-interpreter"
main = "src/index.js"  
compatibility_date = "2024-01-01"
node_compat = true       
account_id = "27a85cdd957c8c26de19d775cf5c8c52" 



[[kv_namespaces]]
binding = "TOKEN_LOGS"
id = "b0deabe9d58344c5a1b3f2acfd6e0e8c"


[env.dev]
name = "tarot-interpreter-dev"