name = "tarot-interpreter"
type = "javascript"
account_id = "27a85cdd957c8c26de19d775cf5c8c52"
main = "src/index.js"
compatibility_date = "2023-10-30"

# Specify environment variables
[vars]
# You can put non-secret environment variables here
# For secrets, use: wrangler secret put API_KEY

# Route configuration
# [routes]
# pattern = "your-domain.com/api/*"
# zone_id = "your-zone-id" # Add this if using a custom domain

# Development environment
[env.dev]
name = "tarot-interpreter-dev"
main = "src/index.js"
[[kv_namespaces]]
binding = "TOKEN_LOGS"
id = "b0deabe9d58344c5a1b3f2acfd6e0e8c"